# permissions to do viewer gitrepos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitrepo-viewer-role
rules:
- apiGroups:
  - git.gitops.slipway.org
  resources:
  - gitrepos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - git.gitops.slipway.org
  resources:
  - gitrepos/status
  verbs:
  - get
