# permissions to do edit gitrepos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitrepo-editor-role
rules:
- apiGroups:
  - git.gitops.slipway.org
  resources:
  - gitrepos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.gitops.slipway.org
  resources:
  - gitrepos/status
  verbs:
  - get
  - patch
  - update
