# permissions to do edit hashes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hash-editor-role
rules:
- apiGroups:
  - git.gitops.slipway.org
  resources:
  - hashes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.gitops.slipway.org
  resources:
  - hashes/status
  verbs:
  - get
  - patch
  - update
