apiVersion: git.gitops.slipway.org/v1
kind: GitRepo
metadata:
  name: gitrepo-sample
spec:
  uri: "git@github.com:jasonrichardsmith/slipway-examples.git"
  gitpath: "github"
  operations:
    - operation: test
      path: "git@github.com:jasonrichardsmith/slipway-examples.git//kustomize/base"
      weight: 3
      optype: branch
      reference: m[a-z]+r
      transformers:
        - type: annotations
          value: branch
          key: branch-name
        - type: namespace
          value: branch
    - operation: test2
      path: "git@github.com:jasonrichardsmith/slipway-examples.git//kustomize/base/"
      hashpath: true
      weight: 3
      optype: branch
      reference: testpr
      transformers:
        - type: namespace
          value: hash
